version: '3'

services:
  # Application

  postgresql:
    image: 'bitnami/postgresql:latest'
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=kore
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  mongo:
    image: 'bitnami/mongodb:latest'
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      - MONGODB_USERNAME=paymetrade
      - MONGODB_PASSWORD=mongo_password_development
      - MONGODB_DATABASE=kore
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis_password_development
    volumes:
      - 'redis_data:/bitnami/redis'

volumes:
  postgresql_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
